/* Generated by the build. Public settings only: the Supabase anon key is designed to be public. */
window.APP_CONFIG = {
  "slug": "trip-planner",
  "name": "Trip Mapper",
  "supabaseUrl": "https://izyyaxovwwvjrladiumv.supabase.co",
  "supabaseAnonKey": "sb_publishable_nCqQWacYrOdTDGU9yspukA_jQvQoc9I",
  "aiProxy": "https://ai-proxy.goede-aeb.workers.dev",
  "google": false,
  "prompts": [
    {
      "say": "Three days in Kyoto in April, temples and food",
      "does": "Plans the trip and maps every stop."
    },
    {
      "say": "Move the castle to day 2 and add lunch near it",
      "does": "Moves the stop and adds a new one nearby."
    },
    {
      "say": "Sam paid 46 euros for dinner, split two ways",
      "does": "Logs the expense and updates who owes whom."
    }
  ]
};
